src/vite/index.ts
src/vite/restart-on-add-unlink.ts

feat: add `restart-on-add-unlink` vite plugin

---

README.md

docs(README): Rename renderer.tsx to _renderer.tsx

---

src/client/client.ts
src/client/runtime.ts
test/hono-jsx/app/routes/interaction/children.tsx
test/hono-jsx/e2e.test.ts

fixes #74
https://github.com/honojs/honox/pull/56 allows the insertion of server components as children. In this PR, in addition to that, if a client component is included as a child, it will be hydrate as a client component.
First, `useReducer` needs to be added by the following PR.
https://github.com/honojs/hono/pull/2197
After that, the pattern using `useReducer()` and "Context API" introduced in the following stackoverflow question can be used to share the state.
https://stackoverflow.com/questions/63687178/sharing-states-between-two-components-with-usereducer
Below is a project that implements this.
https://github.com/usualoma/honox-jsx-children
```ts
import { createRoute } from "honox/factory";
import Producer from "../islands/producer";
import Consumer from "../islands/consumer"; …
```

feat: add support for client component in children

---

package.json
src/server/base.ts
src/server/index.ts
src/server/server.ts
src/server/with-defaults.ts

If the user implementation includes `import { createApp } from "honox/server"`, all routes are included in the bundle by the hardcoded `import.meta.glob`.
Even if the user gives the option of `createApp` to overwrite it, the hardcoded part is still there and will not be removed by DCE.
With this change, `import { createApp } from "honox/server/base"` can be used to bypass the hardcoded parts and control all bundled routes by the options we give.
This change also allows builds that only return dynamic routes from Cloudflare Workers, without unnecessary routes which is already SSGed.
(We still need to work, due to [current `@hono/vite-cloudflare-pages` cannot serve SSGed files](https://github.com/honojs/vite-plugins/blob/551e8801c2450f1723a51318e489a83b95798887/packages/cloudflare-pages/src/ …

feat: add createApp without default routes

---

README.md

This PR resolves #106 by adding a guide & code example for passing `ContextRenderer` props from nested renderers to their parents.

docs(README): add guide for passing nested layout props

---

README.md

docs(readme): add `context in islands` and format

---

src/server/with-defaults.ts

Enabled colocated test files in routes by excluding *.test.* and *.spec.* from routing recognition.

feat: exclude *.test.* and *.spec.* files in routes

---

test/hono-jsx/playwright.config.ts

Fixes `playwright` not running without the `bun` command. It is not smart, but this method is the most universal.

chore: fix `vite` path in playwright config

---

README.md
src/server/server.ts
src/server/with-defaults.ts
test/hono-jsx/app-nested/routes/top.tsx
test/hono-jsx/integration.test.ts

feat: add `trailingSlash` option

---

mocks/app-nested-middleware/routes/nested/foo/bar/[id]/index.tsx
src/utils/file.test.ts
src/utils/file.ts
test-integration/api.test.ts
test-integration/apps.test.ts

Fixed a problem if the path has brackets overriding other directory paths in the same hierarchy.

fix: correct routing priority if file name has brackets

---

src/utils/file.ts

Hi @yusukebe!
Sorry for the boring change suggestion. Sorting is an expensive process and I would prefer it to be done once.

refactor: simplify sortDirectoriesByDepth function

---

mocks/app/routes/directory/_Counter.island.tsx
mocks/app/routes/directory/index.tsx
mocks/vite.config.ts
src/client/client.ts
src/vite/inject-importing-islands.ts
src/vite/island-components.ts
test-e2e/e2e.test.ts
test-integration/apps.test.ts
test-integration/vitest.config.ts

Related to #45 
With this PR, you can put an island component in a directory under `/app/routes`, not only the `/app/islands` directory. You should name it with a `_` prefix, like `_counter.island.tsx`.
```
app
├── client.ts
├── global.d.ts
├── islands
│   └── counter.tsx
├── routes
│   ├── directory
│   │   ├── _counter.island.tsx // <--- You can put it here
│   │   └── index.tsx
│   ├── index.tsx
└── server.ts
```
It was inefficient to put Islands in `/app/islands`, which are used only in a certain directory. However, this PR makes it easier to understand the structure by placing Islands in the same directory as the files that use them.

feat: enable to put "island" not only in `islands` directory

---

mocks/app/islands/Badge.tsx
mocks/app/islands/Counter.tsx
src/vite/island-components.ts
test-integration/apps.test.ts

fix #150 
With this change, nested islands will behave as one island.
New HTML:

fix: nested islands ssr

---

src/vite/island-components.ts

Fixes #152
It's difficult to write tests. Skipping it right now.

fix: check it should add `insideIslandSuffix` or not

---

tsup.config.ts

On Windows, could not build HonoX as shown below.
```bash
$ ❯ bun run build
$ tsup && publint
Cannot find src\types.ts,src\index.ts,src\constants.ts,src\vite\restart-on-add-unlink.ts,src\vite\island-components.ts,src\vite\island-components.test.ts,src\vite\inject-importing-islands.ts,src\vite\index.ts,src\vite\client.ts,src\vite\components\index.ts,src\vite\components\honox-island.tsx,src\utils\file.ts,src\utils\file.test.ts,src\server\with-defaults.ts,src\server\server.ts,src\server\index.ts,src\server\base.ts,src\server\components\script.tsx,src\server\components\index.ts,src\server\components\has-islands.tsx,src\factory\index.ts,src\factory\factory.ts,src\client\runtime.ts,src\client\index.ts,src\client\client.ts
error: script "build" exited with code 1
```
This PR enables builds by …

fix(windows): failed to build honox on Windows

---

src/server/components/has-islands.tsx
src/server/components/script.tsx
src/server/context-storage.ts
src/server/server.ts
src/vite/island-components.test.ts
src/vite/island-components.ts
test-integration/api.test.ts
test-integration/apps.test.ts

#167
This appears to be a good and simple solution to implement.
However (I am not familiar with Cloudflare Workers, so maybe there is another solution) it appears that `compatibility_flags = [ "nodejs_compat"]` needs to be added to wrangler.toml.

feat: `Script` and `HasIsland` available at multiple runtimes with `AsyncLocalStorage`

---

mocks/app/routes/directory/$counter.tsx
mocks/app/routes/directory/index.tsx
src/vite/island-components.test.ts
src/vite/island-components.ts
test-e2e/e2e.test.ts
test-integration/apps.test.ts
test-integration/vitest.config.ts

With this PR, the component file whose name has `$` as a prefix, like `/app/routes/dir/$counter.tsx`, will be treated as an island component.
Before this PR, the filenames which are island components are below:
1. Under `/islands` - `/islands/conter.tsx`
2. An underscore and `.island.tsx` suffix - `/app/routes/dir/_counter.island.tsx`
From my experience using HonoX, it's sometimes easy to handle if the island component is in the same directory with the route file. So the `2` is better. But I'd make it a simpler and shorter name.
3. `$` prefix - `/app/routes/dir/$counter.tsx`
Why `$` - this is just my taste, but I think it's easy to understand.
---
I'll work on #159 after merging this PR.

feat: `$` prefix named file as island component

---

mocks/app/components/$counter.tsx
mocks/app/routes/interaction/anywhere.tsx
mocks/vite.config.ts
src/client/client.ts
src/vite/inject-importing-islands.ts
src/vite/island-components.test.ts
src/vite/island-components.ts
src/vite/utils/path.test.ts
src/vite/utils/path.ts
test-e2e/e2e.test.ts
test-integration/apps.test.ts
test-integration/vitest.config.ts

With this PR, we can put island components anywhere instead of under `/app/routes` or `/app/islands`. For example, the components placed like the following will be treated as islands.
* `/app/components/$counter.tsx`
* `/app/components/_counter.island.tsx`
In addition, I've added the following changes:
* Made it islands directory only `^/islands` or specify the path if passing the option.
* Corrected importing path of client components in the client.
* Simplify some options.
* Fixed resolving alias path.
* Added some missing tests.
Fixes #159

feat: enable placing islands anywhere

---

mocks/app-link/routes/_renderer.tsx
mocks/app-link/routes/classic/index.tsx
mocks/app-link/routes/index.tsx
src/server/components/index.ts
src/server/components/link.tsx
test-integration/apps.test.ts

For example, you may want to use TailwindCSS for styling HonoX components. Currently, it is possible to develop using the `<link />` tag, but the build result does not contain a unique value such as a file hash, which can lead to unintended caching.
This PR addresses such a use case.
As an example, we are considering the following use cases:
```tsx
// _renderer.tsx
import { jsxRenderer } from "hono/jsx-renderer";
import { Script, Link } from "honox/server";
export default jsxRenderer(() => {
return (
<html lang="en">
<head>
<Link href="/app/globals.css" rel="stylesheet" />
</head>
<body class="bg-white">
{/* omitted... */}
</body>
</html>
);
});
// vite.config.ts
import { defineConfig } from "vite";
export default defineConfig(({ mode }) => {
if (mode === "client") {
return {
build: { …
```

feat: add `Link` component for external (built) css

---

src/server/utils/file.ts
src/server/with-defaults.ts

This PR adds `.md` as a route file extension and also supports omission of the extension.
This should be provided as a config so that other extensions can do this, but [vite does not support it](https://vitejs.dev/guide/features#:~:text=You%20can%20NOT%20use%20variables%20or%20expressions%20in%20them.).
closes: #187

feat: support `.md`

---

mocks/app/routes/directory/_error.tsx
mocks/app/routes/directory/sub/throw_error.tsx
mocks/app/routes/directory/throw_error.tsx
src/server/server.ts
test-integration/apps.test.ts

feat: cascading error pages

---

src/vite/client.ts
src/vite/index.ts

Then you don't have to write:
```ts
export default defineConfig(({ mode }) => {
if (mode === 'client') {
return {
build: {
rollupOptions: {
input: ['/app/style.css']
}
},
plugins: [clientBuild()]
}
} else {
return {
plugins: [
honox({
devServer: {
adapter
}
}),
ssrBuild()
]
}
}
})
```
Instead of it, you can write it shortly:
```ts
export default defineConfig({
plugins: [
honox({
devServer: {
adapter
},
client: {
input: ['/app/style.css']
}
}),
pages()
]
})
```

feat: add `client` plugin to `honox/vite`

---

src/server/with-defaults.ts

[RFC6920 defines](https://www.rfc-editor.org/rfc/rfc6920.html#section-8.1) some well-known routes like:
http://example.com/.well-known/ni/sha-256/f4OxZX_x_FO5LcGBSKHWXfwtSx-j1ncoSt3SABJtkGk
Note that there are three path segments after the `/.well-known/` path prefix.
In my honox /app directory, I crated `/app/routes/.well-known/ni/[alg]/[val].tsx` but it didn't work. (it does work if I directly nest at `/app/routes/.well-known/[val].tsx`).
Based on cursory local testing of this change. I think this change accomodates for several path segments beyond `/.well-known/` as well as only one.

fix: default routes include well-known URIs with several path segments

---

package.json

I added my fork of this repo to my project as a npm git dependency, but it didn't work until I did this.
https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts
> NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.

add "prepare" npm script so this works when depended on via git link

---

mocks/app/routes/about/[name]/_renderer.tsx
mocks/app/routes/about/[name]/hobbies/[hobby_name]/_middleware.ts
mocks/app/routes/about/[name]/hobbies/[hobby_name]/index.tsx
src/server/server.ts
test-integration/apps.test.ts

fix: support `_middleware.ts` for deeply nested param routes

---

mocks/app/server.ts

This pull request fixes NOT_FOUND regex for `mocks/app/server.ts`.

chore: fixed NOT_FOUND regex for mocks server

---

src/server/components/link.tsx

`<Link />` is an async component in spite of unnecessary and because of this causes following error in Deno:
```
A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
at renderToStringImpl (file:///Users/234531sch/Library/Develops/github.com/4513ECHO/etude-honox-deno/node_modules/.deno/react-dom@19.0.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7125:15)
at process.env.NODE_ENV.exports.renderToString …
```

fix: Make `<Link />` not async

---

src/vite/island-components.test.ts
src/vite/island-components.ts

When I use HonoX from Deno, I got an error that vite cannot read tsconfig.json because Deno does not support tsconfig.json but directly deno.json.
I have added deno.json support to HonoX.

fix: Read deno.json in islandComponents vite plugin

---

src/vite/island-components.test.ts
src/vite/island-components.ts

Related: #249 
#249 supported for deno.json, but not deno.jsonc. This PR will support for that.
I removed the errors from `console.warn`, but I will add it if necessary.
There are too many errors to display, so we need some ingenuity.

feat: support for deno.jsonc in vite plugin

---

src/server/components/link.tsx
src/server/components/script.tsx
src/server/utils/path.test.ts
src/server/utils/path.ts
test-integration/apps.test.ts

fixes #243 partially
> The problem occurs because the .js file references in each HTML are written as root-relative paths. If the deployment destination is a subpath (e.g., GitHub Pages), the subpath segment must be included when referencing root-relative paths.
>
> When deploying to https://example.com/path/to/some/dir/, the following mismatch arises, causing the .js file to fail to load:
>
> | Reference in the output HTML |Actual file path = Correct reference |
> |----|----|
> |`/static/client-${hash}.js`|`/path/to/some/dir/static/client-${hash}.js`|
This PR enables deployment to subpaths such as GitHub Pages. See https://vite.dev/config/shared-options#base https://vite.dev/guide/env-and-mode#env-variables

feat: Support subpath deployment

---

README.md

Additional note: it also seems to work if I just export an array of those middlewares. Do we really need to wrap them with createRoute?
```
export default [
secureHeaders({
contentSecurityPolicy: {
scriptSrc: [NONCE]
}
})
];
```

docs: update secureHeaders example

---

README.md
mocks/app-route-groups/routes/_renderer.tsx
mocks/app-route-groups/routes/blog/(content-group)/_middleware.ts
mocks/app-route-groups/routes/blog/(content-group)/_renderer.tsx
mocks/app-route-groups/routes/blog/(content-group)/hello-world.mdx
mocks/app-route-groups/routes/blog/index.tsx
mocks/app-route-groups/routes/index.tsx
mocks/app-route-groups/server.ts
src/server/server.ts
src/server/utils/file.test.ts
src/server/utils/file.ts
test-integration/apps.test.ts

Enable/allow routes to have grouping without adjusting their path. eg.:
Given structure
```
app/
routes/
index.ts
blog/
index.ts
(content)/ # not added to the actual path
_renderer.tsx
_middleware.ts
lorem-ipsum.mdx
hello-world.mdx
```
| Path              | Route File                      |
|-------------------|---------------------------------|
| /                 | index.ts                        |
| /blog             | /blog/index.ts                  |
| /blog/lorem-ipsum | /blog/(content)/lorem-ipsum.mdx |
| /blog/hello-world | /blog/(content)/hello-world.mdx |
Routes in `(content)` also has `_renderer.tsx` and `_middleware.ts` applied to them, but not to route in parent directory (`/blog`)
This solves https://github.com/honojs/honox/issues/237, just in different solution - `(name)` …

feat: Route grouping

---

README.md

Hello. Thank you for your nice project.
This PR adds a new subsection into the section of React in the README demonstrating how to use the recently introduced `<Script />` tag for manifest-based script injection.
I have considered wholely replacing the section since it's more simple way to use the `<Script />` tag (according to [the article](https://zenn.dev/yusukebe/articles/4d6297f3be121a#scriptとlinkコンポーネント), you know) in recent HonoX, but for now I'll just add the subsection.

docs(readme): add Config of React with `<Script />`

---

src/vite/index.ts

devServerDefaultOptions in this file doesn't have the exclusions below:
- /^\/app\/.+\.tsx?/,
- /^\/favicon.ico/,
- /^\/static\/.+/,
The behavior is a little bit confusing.

refactor: default dev server options should include the honox default.

---

README.md
src/vite/client.ts

fix(vite/client): ensure defaultOptions are required and client input can be overwritten
