src/utils/file.ts, test/unit/utils/file.test.ts
=> fix(util): replace `index.get.tsx` to `index.get` correctly

src/utils/file.ts, test/unit/utils/file.test.ts
=> fix(util): support more than one path params

src/client/runtime.ts, test/hono-jsx/app/routes/interaction/children.tsx, test/hono-jsx/app/routes/interaction/error-boundary.tsx, test/hono-jsx/e2e.test.ts
Fixes https://github.com/honojs/honox/issues/47
=> fix: build props from child node's attributes for intrinsic elements

README.md
Resolve #48 
These samples require https://github.com/honojs/vite-plugins/releases/tag/%40hono%2Fvite-ssg%400.1.0
=> docs(README): update SSG sample + add client

src/vite/island-components.ts, test/unit/vite/island-components.test.ts
What about making it available for unnamed functions?
=> feat: support unnamed default export

README.md
Fix forgotten import of HasIslands
=> fix: HasIslands import

src/vite/index.ts, src/vite/island-components.ts, test/hono-jsx/app/components/islands/not-island.tsx, test/hono-jsx/app/routes/non-interactive.tsx, test/hono-jsx/integration.test.ts, test/hono-jsx/vite.config.ts, test/hono-jsx/vitest.config.ts
=> feat: do not make `/app/components/islands/foo.tsx` Island component

mocks/app-nested-middleware/routes/_middleware.ts, mocks/app-nested-middleware/routes/index.tsx, mocks/app-nested-middleware/routes/nested/_middleware.ts, src/server/server.ts, src/utils/file.ts, test-integration/apps.test.ts
Correct setting top level-middleware and not found handlers.
=> fix: correct routing priority

mocks/app-script/routes/_nonce_renderer.tsx, src/server/components/script.tsx, test-integration/apps.test.ts
https://github.com/honojs/honox/issues/157
It is more effective when used together with https://github.com/honojs/hono/pull/2577
=> feat: Enable to pass nonce to script component

mocks/app/routes/about/[name]/_middleware.ts, src/server/server.ts, test-integration/apps.test.ts
=> fix: `_middleware` in param routes

src/server/with-defaults.ts
=> fix: ignore dollar files as routes

README.md
React rendering docs is incomplete.
=> docs: complete react rendering configuration

README.md
related to honojs/vite-plugins#201, honojs/vite-plugins#202
=> docs: update README - secureHeaders/nonce usage

mocks/app/routes/app/nested/index.tsx, src/vite/index.ts, test-e2e/e2e.test.ts, test-integration/apps.test.ts
=> fix: exclude `/^\/app\/.+\.tsx?/` in vite dev-server

README.md
HonoX with TailwindCSS v3 guide -> HonoX with TailwindCSS v4 guide
=> docs: update TailwindCSS v4 guide

mocks/app-function/routes/api-response.tsx, mocks/app-function/routes/async-jsx.tsx, mocks/app-function/routes/async-response.tsx, mocks/app-function/routes/jsx-response.tsx, src/server/server.ts, test-integration/apps.test.ts
=> feat: add support for `Response` in component routing

bun.lock, mocks/app/routes/not-found.tsx, package.json, src/server/server.ts, test-integration/apps.test.ts
=> fix: `c.notFound()` returns `_404.txt` content

README.md, src/server/with-defaults.ts
=> feat: exclude files and directories starting with a `-` from routing

mocks/app-nested-middleware/routes/admin/_middleware.ts, mocks/app-nested-middleware/routes/admin/dashboard/index.tsx, mocks/app-nested-middleware/routes/admin/dashboard/settings/index.tsx, src/server/server.ts, test-integration/apps.test.ts
=> fix: middleware not applied when directory has no other files

mocks/app-route-groups/routes/(static)/(legal)/privacy-policy/index.tsx, src/server/utils/file.test.ts, src/server/utils/file.ts, test-integration/apps.test.ts
Fixes #300
While I was creating this PR, #301 was created with the same purpose. My PR has more thorough testing, but I referred the implementation of #301. Therefore, I add @sahithyandev as a co-author to this PR. Thanks!
=> fix: correct nested grouping url

mocks/app-nested-middleware/routes/without-route/_middleware.ts, mocks/app-nested-middleware/routes/without-route/with-index/index.tsx, mocks/app-nested-middleware/routes/without-route/with-named/named.tsx, src/client/runtime.test.ts, src/server/server.ts, src/server/utils/file.ts, src/vite/components/honox-island.test.tsx, test-integration/apps.test.ts
=> fix: fixes middleware not being applied inside nested folder where the parent folder has no route
